name: Deploy using Terragrunt

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: false
        default: us-east-1
        type: string
      ENVIRONMENT:
        required: true
        type: string

jobs:
  check-file-changes:
    name: Create JSON_Matrix with changed files path
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create JSON
        id: json
        run: |
          output_json=$(./create_json.sh ${{ inputs.ENVIRONMENT }})
          echo "json_matrix=$output_json" >> "$GITHUB_OUTPUT"
          echo "$output_json"
    outputs:
      json_matrix: ${{ steps.json.outputs.json_matrix }}

  deploy:
    name: Deploy AWS via Terragrunt
    runs-on: ubuntu-latest
    needs: check-file-changes
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.check-file-changes.outputs.json_matrix) }}
    env:
      AWS_REGION: ${{ inputs.AWS_REGION }}
      ENV: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch_dept: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.AWS_REGION }}
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Terragrunt
        uses: userbradley/action-install-terragrunt@v1.1.1
        with:
          version: "v0.36.12"
      - name: Terragrunt Plan
        run: terragrunt plan -lock=false --terragrunt-non-interactive
        working-directory: ${{ matrix.targets }}
        #working-directory: ${{ github.workspace }}/infra/environments/${{ inputs.ENVIRONMENT }}/ ${{ matrix.directories }}
