name: Deploy using Terragrunt

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: false
        default: us-east-1
        type: string
      ENVIRONMENT:
        required: true
        type: string

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ inputs.AWS_REGION }}
      ENV: ${{ inputs.ENVIRONMENT }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch_dept: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.AWS_REGION }}
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
          pwd
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Terragrunt
        uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: 0.36.12
      - name: Terragrunt Plan
        run: terragrunt plan -lock=false --terragrunt-non-interactive=true
        working-directory: ${{ github.workspace }}/infra/environments/${{ inputs.ENVIRONMENT }}/
